name: CI
on:
  push:

permissions:
  contents: read
  packages: write

env:
  TAG_VER: 2

jobs:
  build-attempt-1:
    runs-on: ubuntu-latest-8
    steps:
      - uses: actions/checkout@v3
      - run: docker version
      - run: docker info
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: ls -la --time-style=full-iso .
      - run: |
          DOCKER_BUILDKIT=1 docker build \
            --progress plain \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg USER_ID=$(id -u) \
            --build-arg GROUP_ID=$(id -g) \
            --label org.opencontainers.image.source=https://github.com/zaleos/docker-cache-dbg \
            -t ghcr.io/zaleos/docker-cache-dbg:$TAG_VER \
            --cache-from ghcr.io/zaleos/docker-cache-dbg:$TAG_VER \
            .
      - run: docker push ghcr.io/zaleos/docker-cache-dbg:$TAG_VER
  
  build-attempt-2:
    runs-on: ubuntu-latest-8
    needs:
      - build-attempt-1
    steps:
      - uses: actions/checkout@v3
      - run: docker version
      - run: docker info
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: ls -la --time-style=full-iso .
      - run: |
          DOCKER_BUILDKIT=1 docker build \
            --progress plain \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg USER_ID=$(id -u) \
            --build-arg GROUP_ID=$(id -g) \
            --label org.opencontainers.image.source=https://github.com/zaleos/docker-cache-dbg \
            -t ghcr.io/zaleos/docker-cache-dbg:$TAG_VER \
            --cache-from ghcr.io/zaleos/docker-cache-dbg:$TAG_VER \
            .
      - run: docker push ghcr.io/zaleos/docker-cache-dbg:$TAG_VER
      